export const user = ''
export const key = ''
export const bsUrliOS = ''
export const bsUrlAndroid = ''
export const username = ''
export const password = ''
export const appiumVersion = ''
export const projectName = ''
export const sprintNumber = ''
export const runNumber = ''
export const buildNameIosTablet = `Sprint ${sprintNumber} - iOS Table - run ${runNumber}`
export const buildNameIosMobile = `Sprint ${sprintNumber} - iOS Mobile - run ${runNumber}`
export const buildNameAndroidTablet = `Sprint ${sprintNumber} - Android Tablet - run ${runNumber}`
export const buildNameAndroidMobile = `Sprint ${sprintNumber} - Android Mobile - run ${runNumber}`
